# Generated by Django 5.0.6 on 2024-06-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_user_stripe',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
